### PR TITLE
based on oci sepc, remove runtime.json and related code

### PR DESCRIPTION
**Pull request by Mashimiao**
Signed-off-by: Ma Shimiao mashimiao.fnst@cn.fujitsu.com

### CODE REVIEW

**Comment by Mashimiao** [comment]
ping @ChengTiesheng

**Comment by ChengTiesheng** [comment]
@Mashimiao Thanks for your contribution:)
Would you like to update Godeps? So we can compile oci2docker just using make.

**Comment by Mashimiao** [comment]
OK, I will update the PR later.

**Comment by Mashimiao** [comment]
ping @ChengTiesheng  please review

**Comment by ChengTiesheng** [comment]
Thanks @Mashimiao :+1: 
LGTM

**Pull request merged**
